id: P2C6C60E2
initial_creation_type: input
source_metadata:
  Title: 'The Caṇḍamahāroṣaṇa tantra: Chapters I-VIII'
  Editor: Christopher Starr George
  Publisher: University of Pennsylvania
  Place of Publication: Pennsylvania, USA
  Year: '1971'
  चण्डमहारोषण तन्त्र:
    Text Version: Devanagari
    Input Personnel: Miroj Shakya
    Input Date: '2018'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Buddhist Studies
    Sponsor: University of the West
created_at: '2022-03-08T17:07:40.697881'
last_modified_at: '2022-03-08T17:07:40.697889'
